In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#importing packages
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

# The necessity to convert data into a list format was a limitation of the first strategy.Storing 1000s data ->it is computationally expensive.
# The Apyori package is no longer supported.

In [ ]:
#importing the data from real E-commerse dataset.
data=pd.read_csv('/content/drive/MyDrive/SIN datasets/data.csv',encoding="ISO-8859-1")

In [ ]:
data.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom

In [ ]:
data.count()

InvoiceNo      541909
StockCode      541909
Description    540455
Quantity       541909
InvoiceDate    541909
UnitPrice      541909
CustomerID     406829
Country        541909
dtype: int64

In [ ]:
data.Country.value_counts()

United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: Country, dtype: int64

In [ ]:
#using the france dataset
data1=data[data.Country=='France']

In [ ]:
data1.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,12/1/2010 8:45,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,12/1/2010 8:45,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,12/1/2010 8:45,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,12/1/2010 8:45,0.85,12583.0,France
30,536370,21883,STARS GIFT TAPE,24,12/1/2010 8:45,0.65,12583.0,France

In [ ]:
data1.value_counts()

InvoiceNo  StockCode  Description                         Quantity  InvoiceDate      UnitPrice  CustomerID  Country
574506     23085      ANTIQUE SILVER BAUBLE LAMP           3        11/4/2011 13:24  10.40      12577.0     France     2
552826     82583      HOT BATHS METAL SIGN                 4        5/11/2011 13:20  2.10       14277.0     France     2
569332     21035      SET/2 RED RETROSPOT TEA TOWELS       1        10/3/2011 13:46  3.25       12637.0     France     2
           22124      SET OF 2 TEA TOWELS PING MICROWAVE   1        10/3/2011 13:46  2.95       12637.0     France     2
           22328      ROUND SNACK BOXES SET OF 4 FRUITS    1        10/3/2011 13:46  2.95       12637.0     France     2
                                                                                                                      ..
554097     22517      CHILDS GARDEN RAKE PINK              6        5/22/2011 13:01  2.10       12567.0     France     1
           22516      CHILDS GARDEN RAKE BLUE              6        5/22/2011 13:01  2.10       12567.0     France     1
           22515      CHILDS GARDEN SPADE PINK             6        5/22/2011 13:01  2.10       12567.0     France     1
           22514      CHILDS GARDEN SPADE BLUE             6        5/22/2011 13:01  2.10       12567.0     France     1
C581316    23174      REGENCY SUGAR BOWL GREEN            -1        12/8/2011 11:46  4.15       12523.0     France     1
Length: 8475, dtype: int64

In [ ]:
#we can also remove some negative quantities.
data1 = data1[data1.Quantity >0]

In [ ]:
data1[data1.Country == 'France'].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,12/1/2010 8:45,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,12/1/2010 8:45,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,12/1/2010 8:45,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,12/1/2010 8:45,0.85,12583.0,France
30,536370,21883,STARS GIFT TAPE,24,12/1/2010 8:45,0.65,12583.0,France
31,536370,10002,INFLATABLE POLITICAL GLOBE,48,12/1/2010 8:45,0.85,12583.0,France
32,536370,21791,VINTAGE HEADS AND TAILS CARD GAME,24,12/1/2010 8:45,1.25,12583.0,France
33,536370,21035,SET/2 RED RETROSPOT TEA TOWELS,18,12/1/2010 8:45,2.95,12583.0,France
34,536370,22326,ROUND SNACK BOXES SET OF4 WOODLAND,24,12/1/2010 8:45,2.95,12583.0,France
35,536370,22629,SPACEBOY LUNCH BOX,24,12/1/2010 8:45,1.95,12583.0,France

In [ ]:
# we need to fill zeros in any NAN Value if mentioned
basket = pd.pivot_table(data=data1,index='InvoiceNo',columns='Description',values='Quantity', \
                        aggfunc='sum',fill_value=0)

In [ ]:
basket.head(20)

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,24,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537468,0,0,0,0,0,0,0,24,0,0,...,0,0,0,0,0,0,0,0,0,0
537693,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537897,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537967,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
538008,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
538093,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
538196,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539050,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,0,0
539113,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539407,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539435,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539551,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539607,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539688,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539727,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#this to check correctness after binning it to 1 at below code..
basket['ALARM CLOCK BAKELIKE PINK'].head(10)

InvoiceNo
536370    24
536852     0
536974     0
537065     4
537463     0
537468     0
537693     0
537897     0
537967     0
538008     0
Name: ALARM CLOCK BAKELIKE PINK, dtype: int64

In [ ]:
basket.head(50)

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,24,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537468,0,0,0,0,0,0,0,24,0,0,...,0,0,0,0,0,0,0,0,0,0
537693,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537897,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537967,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
538008,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
538093,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
538196,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539050,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,0,0
539113,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539407,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539435,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539551,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539607,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539688,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539727,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
539829,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540178,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540239,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540351,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540365,0,0,0,0,0,0,0,24,0,0,...,0,0,0,0,0,0,0,0,0,0
540455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540521,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540642,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540688,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540789,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540824,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540835,0,0,0,0,0,0,0,24,0,0,...,0,0,0,0,0,0,0,0,0,0
540851,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540972,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
540976,0,0,0,0,6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
541120,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
541121,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
541138,0,0,0,0,0,0,0,24,0,0,...,0,0,0,0,0,0,0,0,0,0
541405,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
541567,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
541631,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
541857,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
541981,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
542132,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
542425,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
542433,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
542535,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
542629,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
542735,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# we dont need quantity sum we need either has taken or not so if user has taken that item mark as 1 else he has not taken 0.

def convert_into_binary(x):
    if x > 0:
        return 1
    else:
        return 0

In [ ]:
basket_sets = basket.applymap(convert_into_binary)

In [ ]:
# above steps we can same item has quantity now converted to 1 or 0.
basket_sets['ALARM CLOCK BAKELIKE PINK'].head()

InvoiceNo
536370    1
536852    0
536974    0
537065    1
537463    0
Name: ALARM CLOCK BAKELIKE PINK, dtype: int64

In [ ]:
basket_sets

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581171,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581279,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#remove postage item as it is just a seal which almost all transaction contain. 
basket_sets.drop(columns=['POSTAGE'],inplace=True)

In [ ]:
basket_sets

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581171,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581279,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#call apriori function and pass minimum support here we are passing 7%. means 7 times in total number of transaction that item was present.
frequent_itemsets = apriori(basket_sets, min_support=0.07, use_colnames=True)

In [ ]:
#it will generate frequent itemsets using two step approch
frequent_itemsets

     support                                           itemsets
0   0.071429                      (4 TRADITIONAL SPINNING TOPS)
1   0.096939                       (ALARM CLOCK BAKELIKE GREEN)
2   0.102041                        (ALARM CLOCK BAKELIKE PINK)
3   0.094388                        (ALARM CLOCK BAKELIKE RED )
4   0.081633                    (BAKING SET 9 PIECE RETROSPOT )
5   0.071429                    (CHILDRENS CUTLERY DOLLY GIRL )
6   0.099490                             (DOLLY GIRL LUNCH BOX)
7   0.096939                          (JUMBO BAG RED RETROSPOT)
8   0.076531                       (JUMBO BAG WOODLAND ANIMALS)
9   0.125000                           (LUNCH BAG APPLE DESIGN)
10  0.084184                      (LUNCH BAG DOLLY GIRL DESIGN)
11  0.153061                          (LUNCH BAG RED RETROSPOT)
12  0.119898                       (LUNCH BAG SPACEBOY DESIGN )
13  0.117347                               (LUNCH BAG WOODLAND)
14  0.142857                (LUNCH BOX WITH CUTLERY RETROSPOT )
15  0.104592                          (MINI PAINT SET VINTAGE )
16  0.102041                  (PACK OF 72 RETROSPOT CAKE CASES)
17  0.081633                          (PAPER BUNTING RETROSPOT)
18  0.168367                   (PLASTERS IN TIN CIRCUS PARADE )
19  0.137755                         (PLASTERS IN TIN SPACEBOY)
20  0.081633                        (PLASTERS IN TIN STRONGMAN)
21  0.170918                 (PLASTERS IN TIN WOODLAND ANIMALS)
22  0.188776                               (RABBIT NIGHT LIGHT)
23  0.096939                      (RED RETROSPOT CHARLOTTE BAG)
24  0.137755                         (RED RETROSPOT MINI CASES)
25  0.071429                         (RED RETROSPOT PICNIC BAG)
26  0.181122                    (RED TOADSTOOL LED NIGHT LIGHT)
27  0.125000                         (REGENCY CAKESTAND 3 TIER)
28  0.086735                 (RETROSPOT TEA SET CERAMIC 11 PC )
29  0.107143               (ROUND SNACK BOXES SET OF 4 FRUITS )
30  0.158163              (ROUND SNACK BOXES SET OF4 WOODLAND )
31  0.076531                (SET/10 RED POLKADOT PARTY CANDLES)
32  0.132653              (SET/20 RED RETROSPOT PAPER NAPKINS )
33  0.137755                      (SET/6 RED SPOTTY PAPER CUPS)
34  0.127551                    (SET/6 RED SPOTTY PAPER PLATES)
35  0.071429                           (SPACEBOY BIRTHDAY CARD)
36  0.125000                              (SPACEBOY LUNCH BOX )
37  0.122449                (STRAWBERRY LUNCH BOX WITH CUTLERY)
38  0.094388                          (TEA PARTY BIRTHDAY CARD)
39  0.073980                           (WOODLAND CHARLOTTE BAG)
40  0.073980  (ALARM CLOCK BAKELIKE PINK, ALARM CLOCK BAKELI...
41  0.079082  (ALARM CLOCK BAKELIKE RED , ALARM CLOCK BAKELI...
42  0.073980  (ALARM CLOCK BAKELIKE RED , ALARM CLOCK BAKELI...
43  0.071429        (SPACEBOY LUNCH BOX , DOLLY GIRL LUNCH BOX)
44  0.089286  (PLASTERS IN TIN SPACEBOY, PLASTERS IN TIN CIR...
45  0.102041  (PLASTERS IN TIN WOODLAND ANIMALS, PLASTERS IN...
46  0.104592  (PLASTERS IN TIN SPACEBOY, PLASTERS IN TIN WOO...
47  0.102041  (SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...
48  0.102041  (SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RE...
49  0.122449  (SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...
50  0.099490  (SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...

In [ ]:
# we have association rules which need to put on frequent itemset. here we are setting based on lift and has minimum lift as 1
rules_mlxtend = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules_mlxtend.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE GREEN),0.102041,0.096939,0.073980,0.725000,7.478947,0.064088,3.283859
1,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE PINK),0.096939,0.102041,0.073980,0.763158,7.478947,0.064088,3.791383
2,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.094388,0.096939,0.079082,0.837838,8.642959,0.069932,5.568878
3,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.096939,0.094388,0.079082,0.815789,8.642959,0.069932,4.916181
4,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE PINK),0.094388,0.102041,0.073980,0.783784,7.681081,0.064348,4.153061

In [ ]:
# rules_mlxtend.rename(columns={'antecedents':'lhs','consequents':'rhs'})

# as based business use case we can sort based on confidance and lift.
rules_mlxtend[ (rules_mlxtend['lift'] >= 4) & (rules_mlxtend['confidence'] >= 0.8) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
2,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.094388,0.096939,0.079082,0.837838,8.642959,0.069932,5.568878
3,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.096939,0.094388,0.079082,0.815789,8.642959,0.069932,4.916181
17,(SET/6 RED SPOTTY PAPER PLATES),(SET/20 RED RETROSPOT PAPER NAPKINS ),0.127551,0.132653,0.102041,0.800000,6.030769,0.085121,4.336735
18,(SET/6 RED SPOTTY PAPER CUPS),(SET/6 RED SPOTTY PAPER PLATES),0.137755,0.127551,0.122449,0.888889,6.968889,0.104878,7.852041
19,(SET/6 RED SPOTTY PAPER PLATES),(SET/6 RED SPOTTY PAPER CUPS),0.127551,0.137755,0.122449,0.960000,6.968889,0.104878,21.556122
20,"(SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...",(SET/6 RED SPOTTY PAPER PLATES),0.102041,0.127551,0.099490,0.975000,7.644000,0.086474,34.897959
21,"(SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...",(SET/20 RED RETROSPOT PAPER NAPKINS ),0.122449,0.132653,0.099490,0.812500,6.125000,0.083247,4.625850
22,"(SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RE...",(SET/6 RED SPOTTY PAPER CUPS),0.102041,0.137755,0.099490,0.975000,7.077778,0.085433,34.489796